_target_: lightning.pytorch.trainer.Trainer

default_root_dir: ${paths.output_dir}

log_every_n_steps: 200

max_epochs: 50

accelerator: gpu
devices: 1

val_check_interval: 1000  # Run validation 4 times per epoch